apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-https
  labels:
    app: ingress-production
  annotations:
    ingress.kubernetes.io/proxy-body-size: "10m"
    kubernetes.io/ingress.class: "nginx"    
    octops.io/multiproxy: "true"
spec:
  rules:
  - host: web.domain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: web-svc
          servicePort: 9001
  - host: web2.domain.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: web-svc
          servicePort: 9001