// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/danieloliveira079/kubebuilder-example/pkg/client/clientset/versioned/typed/operator/v1beta1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeOperatorV1beta1 struct {
	*testing.Fake
}

func (c *FakeOperatorV1beta1) Medusas(namespace string) v1beta1.MedusaInterface {
	return &FakeMedusas{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeOperatorV1beta1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
