// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// MedusaListerExpansion allows custom methods to be added to
// MedusaLister.
type MedusaListerExpansion interface{}

// MedusaNamespaceListerExpansion allows custom methods to be added to
// MedusaNamespaceLister.
type MedusaNamespaceListerExpansion interface{}
